export const iconList = [
  { name: "旅行", path: require("@/views/images/icon/1157.png") },
  { name: "旅行(赤)", path: require("@/views/images/icon/r1157.png") },
  { name: "旅行(緑)", path: require("@/views/images/icon/g1157.png") },
  { name: "旅行(青)", path: require("@/views/images/icon/b1157.png") },
  { name: "旅行(黄)", path: require("@/views/images/icon/y1157.png") },
  { name: "旅行(黒)", path: require("@/views/images/icon/n1157.png") },
  { name: "鳩とオリーブ", path: require("@/views/images/icon/1194.png") },
  { name: "鳩とオリーブ(赤)", path: require("@/views/images/icon/r1194.png") },
  { name: "鳩とオリーブ(緑)", path: require("@/views/images/icon/g1194.png") },
  { name: "鳩とオリーブ(青)", path: require("@/views/images/icon/b1194.png") },
  { name: "鳩とオリーブ(黄)", path: require("@/views/images/icon/y1194.png") },
  { name: "鳩とオリーブ(黒)", path: require("@/views/images/icon/n1194.png") },
  { name: "笑顔", path: require("@/views/images/icon/0427.png") },
  { name: "笑顔(赤)", path: require("@/views/images/icon/r0427.png") },
  { name: "笑顔(緑)", path: require("@/views/images/icon/g0427.png") },
  { name: "笑顔(青)", path: require("@/views/images/icon/b0427.png") },
  { name: "笑顔(黄)", path: require("@/views/images/icon/y0427.png") },
  { name: "笑顔(黒)", path: require("@/views/images/icon/n0427.png") },
  { name: "プレゼン", path: require("@/views/images/icon/1198.png") },
  { name: "プレゼン(赤)", path: require("@/views/images/icon/r1198.png") },
  { name: "プレゼン(緑)", path: require("@/views/images/icon/g1198.png") },
  { name: "プレゼン(青)", path: require("@/views/images/icon/b1198.png") },
  { name: "プレゼン(黄)", path: require("@/views/images/icon/y1198.png") },
  { name: "プレゼン(黒)", path: require("@/views/images/icon/n1198.png") },
]
